name: Plugin asset/readme update
on:
  push:
    branches:
      - master
    paths:
      - .wporg/*
      - readme.txt
jobs:
  master:
    name: Push to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: bluehost/wp-plugin-readme-assets-updater@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          ASSETS_DIR: .wporg
